import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Old Games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">Old Games Collection</a>
        </h1>

        <div className={styles.grid}>
          <a href="/tictactoe" className={styles.card}>
            <h2>Tic Tac Toe &rarr;</h2>
            <p>Click here to play Tictac toe.</p>
          </a>
        </div>
      </main>
    </div>
  )
}
